Mail 210111
lithekod/user-database pull request #10
Opened 2021-01-11 16:37 UTC by sornas

2021-01-11 17:40 UTC, FredTheDino approved these changes
LGTM, just translate.

2021-01-11 17:40 UTC, FredTheDino commented on email-templates/210111.html
> +      <!-- TODO introduktion -->
```suggestion
      Nytt år, nya möjligheter! Sök styrelsen, git-workshop, IMPA, gå på Game Jam. Ett hav av möjligeheter liger framför er, dags att ta tag i rodret.
```

2021-01-12 09:56 UTC, EMattfolk commented on email-templates/210111.html
> +             på meetupen (om intresset finns) gå igenom hur systemen (UVA, IMPA
```suggestion
             (om intresset finns) gå igenom hur systemen (UVA, IMPA
```

2021-01-12 09:56 UTC, EMattfolk commented on email-templates/210111.html
> +             Nästa gamejam är Global Game Jam (GGJ) som går av stapeln 29-31
går av stapeln?

2021-01-12 09:56 UTC, EMattfolk commented on email-templates/210111.html
> +             Jam håller i en sådan i Linköping. Kolla
```suggestion
             Jam håller i eventet i Linköping. Kolla
```

2021-01-12 09:56 UTC, EMattfolk commented on email-templates/210111.html
> +             <!-- TODO länk -->
```suggestion
             Kolla in <a href="https://lithekod.se/git/se">lithekod.se/git</a> för mer information.
```

2021-01-13 08:59 UTC, th3tard1sparadox requested changes

2021-01-13 08:59 UTC, th3tard1sparadox commented on email-templates/210111.html
> +      och/eller gå på game jam. Ett hav av möjligheter ligger framför er. Dags
```suggestion
      och/eller gå på Game Jam. Ett hav av möjligheter ligger framför er. Dags
```

2021-01-13 08:59 UTC, th3tard1sparadox commented on email-templates/210111.html
> +             att lösa och kammade hem vinsten!
```suggestion
             att lösa och kammade hem största vinsten!
```

2021-01-13 08:59 UTC, th3tard1sparadox commented on email-templates/210111.html
> +             måndag (18 januari). På meetupen dagen efter (19 januari) kommer vi
```suggestion
             måndag (18e januari). På meetupen dagen efter (19e januari) kommer vi
```

2021-01-13 08:59 UTC, th3tard1sparadox commented on email-templates/210111.html
> +             (om intresset finns) gå igenom hur systemen (UVA, IMPA
```suggestion
             --om intresset finns--gå igenom hur systemen (UVA, IMPA
```

2021-01-13 08:59 UTC, th3tard1sparadox commented on email-templates/210111.html
> +             Nästa gamejam är Global Game Jam (GGJ) 29-31
```suggestion
             Nästa Game Jam är Global Game Jam (GGJ) 29e-31a
```

2021-01-13 08:59 UTC, th3tard1sparadox commented on email-templates/210111.html
> +             januari. GGJ är som namnet antyder ett globalt gamejam med
```suggestion
             januari. GGJ är som namnet antyder ett globalt Game Jam med
```

2021-01-13 08:59 UTC, th3tard1sparadox commented on email-templates/210111.html
> +             I vår ska en ny styrelse väljas in men redan nu är ansökan öppen.
```suggestion
             I vår ska en ny styrelse väljas in, men redan nu är ansökan öppen!
```

2021-01-13 08:59 UTC, th3tard1sparadox commented on email-templates/210111.html
> +             solve and managed to win the competition!
```suggestion
             solve and managed to come first in the competition!
```

2021-01-13 08:59 UTC, th3tard1sparadox commented on email-templates/210111.html
> +             18th). During the meetup the day after (January 19th) we will (if
```suggestion
             18th). During the meetup the day after (January 19th) we will --if
```

2021-01-13 08:59 UTC, th3tard1sparadox commented on email-templates/210111.html
> +             anyone wants us to) walk through how the different systems (UVA,
```suggestion
             anyone wants us to--walk through how the different systems (UVA,
```

2021-01-13 08:59 UTC, th3tard1sparadox commented on email-templates/210111.html
> +             The next game jam is Global Game Jam (GGJ) between the January 29th
```suggestion
             The next Game Jam is Global Game Jam (GGJ) between the January 29th
```

2021-01-13 08:59 UTC, th3tard1sparadox commented on email-templates/210111.html
> +             and LiTHe kod's game jam group LiU Game Jam will hold an event in
```suggestion
             and LiTHe kod's Game Jam group LiU Game Jam will hold an event in
```

2021-01-13 08:59 UTC, th3tard1sparadox commented on email-templates/210111.html
> +             <!--TODO fundersamma --> students.  git is a widely used version
```suggestion
             curious and/or frustrated students.  git is a widely used version
```

2021-01-13 08:59 UTC, th3tard1sparadox commented on email-templates/210111.html
> +             <!--TODO kandidatarbete -->. If you've already heard about git and
```suggestion
             Bachelor’s thesis. If you've already heard about git and
```

2021-01-13 08:59 UTC, th3tard1sparadox commented on email-templates/210111.html
> +             blames. <a href="https://lithekod.se/git/en">Mer information finns
```suggestion
             blames. <a href="https://lithekod.se/git/en">More information available
```

2021-01-13 08:59 UTC, th3tard1sparadox commented on email-templates/210111.html
> +             på vår hemsida.</a>
```suggestion
             at our website.</a>
```

2021-01-13 08:59 UTC, th3tard1sparadox commented on email-templates/210111.html
> +             This spring a new board will be voted in but applications are
```suggestion
             This spring a new board will be voted in, and applications are
```

2021-01-13 08:59 UTC, th3tard1sparadox commented on email-templates/210111.html
> +             already open. Joining the board is great way to give something back
```suggestion
             already open! Joining the board is great way to give something back
```

2021-01-13 11:44 UTC, th3tard1sparadox approved these changes
Bara lite små saker, annars ser den toppen ut!

2021-01-13 11:44 UTC, th3tard1sparadox commented on email-templates/210111.html
> +             arrangörer över hela världen och LiTHe kods gamejam-grupp LiU Game
```suggestion
             arrangörer över hela världen och LiTHe kods Game Jam-grupp LiU Game
```

2021-01-13 11:44 UTC, th3tard1sparadox commented on email-templates/210111.html
> +             curious and/or frustrated students. git is a widely used version
```suggestion
             curious and/or frustrated students. Git is a widely used version
```

2021-01-13 11:44 UTC, th3tard1sparadox commented on email-templates/210111.html
> +             curious and/or frustrated students. git is a widely used version
Början på en mening

2021-01-14 11:42 UTC, FredTheDino approved these changes
LGTM

2021-01-14 11:42 UTC, FredTheDino commented on email-templates/210111.html
> +             February 3rd we will hold an introductory git-workshop for
```suggestion
             On the 3rd of February we will hold an introductory git-workshop for
```

2021-01-14 14:46 UTC, merged